# Generated by Django 3.2.12 on 2022-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hayvan',
            name='yaş',
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='açıklama',
            field=models.TextField(verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='cins',
            field=models.CharField(max_length=50, verbose_name='Cinsi'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='dogumtarihi',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='isim',
            field=models.CharField(max_length=50, verbose_name='İsmi'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='tür',
            field=models.CharField(max_length=50, verbose_name='Türü'),
        ),
    ]
